name: MuleSoft CI/CD

on:
  push:
    branches:
      - develop
      - qa
      - sandbox
  pull_request:
    branches: [ develop ]
    types: [ closed ]
  workflow_dispatch: # Manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Determine deployment environment
        id: set-env
        run: |
          # Default CloudHub target (same for all)
          echo "target=Cloudhub-US-East-2" >> $GITHUB_OUTPUT
          
          # Map branch → environment and app name
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            echo "env_name=dev" >> $GITHUB_OUTPUT
            echo "app_name=sravani-reddy-poc-app-dev" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "qa" ]]; then
            echo "env_name=qa" >> $GITHUB_OUTPUT
            echo "app_name=sravani-reddy-poc-app-qa" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "sandbox" ]]; then
            echo "env_name=sandbox" >> $GITHUB_OUTPUT
            echo "app_name=sravani-reddy-poc-app-sandbox" >> $GITHUB_OUTPUT
          fi

      - name: Publish to Exchange
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

      - name: Deploy to CloudHub 2.0
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -Denv="${{ steps.set-env.outputs.env_name }}" \
          -Dtarget="${{ steps.set-env.outputs.target }}" \
          -DapplicationName="${{ steps.set-env.outputs.app_name }}" \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
          -Ddecryption.key="${{ secrets.DECRYPTION_KEY }}"
